#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_INDEX_BLOC = descriptor.Descriptor(
  name='Bloc',
  full_name='indexator.Index.Bloc',
  filename='indexator/index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='indexator.Index.Bloc.data', index=0,
      number=1, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_INDEX = descriptor.Descriptor(
  name='Index',
  full_name='indexator.Index',
  filename='indexator/index.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='size', full_name='indexator.Index.size', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blocs', full_name='indexator.Index.blocs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INDEX.fields_by_name['blocs'].message_type = _INDEX_BLOC

class Index(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Bloc(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _INDEX_BLOC
  DESCRIPTOR = _INDEX

